'use client';
import { useDeferredValue, useEffect, useMemo, useState, useSyncExternalStore } from 'react';
import { ArrowDownToLine, ArrowRight, Building2, Database, IndianRupee, Search, ShieldCheck, SlidersHorizontal, Users } from 'lucide-react';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { compactMoney, money } from '@/lib/domain';
import { columns, decodeRows, emptyFilters, filterWorks, groupWorks, sourceCsv, type Filters, type Manifest, type Work } from '@/lib/mplads';
import { SideNav } from './dashboard';
import CivicBanner from './civic-banner';
import ProjectReviews from './project-reviews';
<<<<<<< HEAD
import ProfileModal from './profile-modal';
=======
import CesiumGlobe from '@/components/geo/CesiumGlobe';
>>>>>>> 745ce73 (Integrate Cesium geo intelligence and satellite view)
function subscribeView(callback:()=>void){window.addEventListener('popstate',callback);return()=>window.removeEventListener('popstate',callback);}
function currentView(){const v=new URLSearchParams(window.location.search).get('view');return v&&titles[v]?v:'overview';}
const count=(n:number)=>n.toLocaleString('en-IN');
const titles:Record<string,string>={overview:'Development overview',projects:'All MPLADS works',map:'Geographic coverage',alerts:'Data review',contractors:'Implementing authorities',feedback:'Citizen feedback',reports:'Reports & insights',data:'Dataset & sources'};
function save(name:string,body:string,type='text/csv;charset=utf-8'){const url=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Picker({value,options,onChange,label}:{value:string;options:string[];onChange:(s:string)=>void;label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="picker" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select>;}
function Badge({text}:{text:string}){return <span className={`badge ${text==='Completed'?'completed':text==='Unsanctioned'||text==='Rejected by IDA'?'medium':'neutral'}`}>{text}</span>;}
function Metric({title,value,note,icon}:{title:string;value:string;note:string;icon:React.ReactNode}){return <article className="metric"><div className="spread"><span>{title}</span><div className="metric-icon">{icon}</div></div><strong className="metric-value">{value}</strong><p>{note}</p></article>;}
function Empty({children}:{children:React.ReactNode}){return <div className="blank"><Database size={28}/><h3>No matching works</h3><p>{children}</p></div>;}

export default function MpladsDashboard({onAdvanced,role='official',user,onLogout,onLoginRequest}:{onAdvanced:()=>void;role?:'citizen'|'official'|'guest';user?:any;onLogout?:()=>void;onLoginRequest?:()=>void}){
 const [showProfile,setShowProfile]=useState(false);
 const [rows,setRows]=useState<Work[]>([]),[manifest,setManifest]=useState<Manifest|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[attempt,setAttempt]=useState(0);
 const view=useSyncExternalStore(subscribeView,currentView,()=> 'overview');
 const [filters,setFilters]=useState<Filters>(role==='citizen'?{...emptyFilters,status:'Ongoing'}:emptyFilters),[advanced,setAdvanced]=useState(false),[page,setPage]=useState(1),[sort,setSort]=useState('Latest recommended'),[selected,setSelected]=useState<Work|null>(null);
 const deferred=useDeferredValue(filters);
 useEffect(()=>{const abort=new AbortController();Promise.all([fetch('/data/mplads.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('Dataset could not be loaded');return r.json() as Promise<{columns:string[];rows:(string|number)[][]}>;}),fetch('/data/mplads-manifest.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('Dataset manifest could not be loaded');return r.json() as Promise<Manifest>;})]).then(([data,info])=>{if(data.rows.length!==info.recordCount||JSON.stringify(data.columns)!==JSON.stringify(columns))throw new Error('Dataset validation failed. Rebuild the bundled data.');setRows(decodeRows(data.rows));setManifest(info);}).catch(e=>{if(!abort.signal.aborted)setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[attempt]);
 const filtered=useMemo(()=>filterWorks(rows,deferred),[rows,deferred]);
 const summary=useMemo(()=>({allocation:filtered.reduce((n,r)=>n+r.allocation,0),completed:filtered.filter(r=>r.status==='Completed').length,mp:new Set(filtered.map(r=>r.mp)).size,pending:filtered.filter(r=>r.approval==='Action Pending').length,missing:filtered.filter(r=>r.status==='Not reported').length}),[filtered]);
 const groups=useMemo(()=>({states:groupWorks(filtered,'state'),statuses:groupWorks(filtered,'status'),approvals:groupWorks(filtered,'approval'),categories:groupWorks(filtered,'category'),months:groupWorks(filtered,'recommended').sort((a,b)=>a.name.localeCompare(b.name)),agencies:groupWorks(filtered,'agency'),mps:groupWorks(filtered,'mp')}),[filtered]);
 const options=useMemo(()=>({states:manifest?.files.map(f=>f.state).sort()||[],categories:[...new Set(rows.map(r=>r.category))].sort(),mps:[...new Set(rows.filter(r=>filters.state==='All states'||r.state===filters.state).map(r=>r.mp))].sort()}),[rows,manifest,filters.state]);
 const sorted=useMemo(()=>[...filtered].sort((a,b)=>sort==='Highest allocation'?b.allocation-a.allocation||a.id.localeCompare(b.id):sort==='Lowest allocation'?b.allocation-b.allocation||a.id.localeCompare(b.id):sort==='Work ID'?a.id.localeCompare(b.id):b.recommended.localeCompare(a.recommended)||a.id.localeCompare(b.id)),[filtered,sort]);
 const pages=Math.max(1,Math.ceil(sorted.length/50)),currentPage=Math.min(page,pages),shown=sorted.slice((currentPage-1)*50,currentPage*50);
 function filter<K extends keyof Filters>(k:K,v:Filters[K]){setFilters(f=>({...f,[k]:v,...(k==='state'?{mp:'All MPs'}:{})}));setPage(1);}
 function navigate(v:string){setPage(1);window.history.replaceState(null,'',`?view=${v}`);window.dispatchEvent(new PopStateEvent('popstate'));window.scrollTo({top:0});}
 function reset(){setFilters(role==='citizen'?{...emptyFilters,status:'Ongoing'}:emptyFilters);setPage(1);}
 function table(data:Work[]){return data.length?<Table><TableHeader><TableRow><TableHead>WORK / LOCATION</TableHead><TableHead>RECOMMENDING MP</TableHead><TableHead>STATUS</TableHead><TableHead>ALLOCATION</TableHead><TableHead>RECOMMENDED</TableHead></TableRow></TableHeader><TableBody>{data.map(r=><TableRow key={r.id}><TableCell><button className="project-link source-project-title" onClick={()=>setSelected(r)}>{r.title||'Description not reported'}</button><div className="secondary">{r.id} · {[r.village||r.city||r.block,r.state].filter(Boolean).join(', ')}</div></TableCell><TableCell><span className="source-mp">{r.mp}</span><div className="secondary">{r.constituency} · {r.house}</div></TableCell><TableCell><Badge text={r.status}/></TableCell><TableCell className="amount">{money(r.allocation)}</TableCell><TableCell>{r.recommended}</TableCell></TableRow>)}</TableBody></Table>:<Empty>Try a different search or <button className="text-button" onClick={reset}>clear filters</button>. Header-only files contain no works.</Empty>;}
 function bars(title:string,data:{name:string;count:number;allocation:number}[],byCount=false,onSelect?:(s:string)=>void){const max=Math.max(1,...data.map(g=>byCount?g.count:g.allocation));return <section className="panel"><div className="panel-heading"><h2>{title}</h2><span className="secondary">{byCount?'Works':'Allocation (INR)'}</span></div><div className="source-bars">{data.length?data.map(g=><div key={g.name}><div className="spread">{onSelect?<button className="text-button" onClick={()=>onSelect(g.name)}>{g.name}</button>:<strong>{g.name}</strong>}<span>{byCount?count(g.count):compactMoney(g.allocation)}</span></div><div className="budget-track"><div style={{width:`${(byCount?g.count:g.allocation)/max*100}%`}}/></div><small className="secondary">{count(g.count)} works{byCount?` · ${compactMoney(g.allocation)} allocated`:''}</small></div>):<p>No records in this selection.</p>}</div></section>;}
 const exportReport=()=>save('mplads-filtered-analysis.json',JSON.stringify({source:manifest?.source,recommendationPeriod:[manifest?.recommendedFrom,manifest?.recommendedTo],filters:deferred,summary:{works:filtered.length,...summary},...groups,definitions:{allocation:'ALLOCATION_AMOUNT in supplied CSV; not expenditure or independently verified sanction value',state:'STATE as supplied; may describe MP affiliation rather than work-site geography',missing:'Unknown fields are not treated as zero'}},null,2),'application/json');
 return <SidebarProvider style={{'--sidebar-width':'252px'} as React.CSSProperties}><SideNav view={view} setView={navigate} alertCount={0} source role={role as any} user={user} onLogout={onLogout} onOpenProfile={()=>setShowProfile(true)}/><main className="workspace source-workspace"><div className="civic-utility"><div><strong lang="hi">सार्वजनिक निर्माण निगरानी</strong><span>Code Crew · SIH prototype</span></div><a href="#main-content">Skip to main content ↓</a></div><header className="topbar"><div className="breadcrumb"><SidebarTrigger/><span className="portal-name">MPLADS Development Monitor<small lang="hi">सांसद स्थानीय क्षेत्र विकास योजना</small></span></div><div className="top-actions"><ShieldCheck size={16}/><span>Supplied dataset</span>{role==='guest'?<button onClick={onLoginRequest} className="button bg-blue-600 text-white border-none ml-4">Login / Sign Up</button>:<div className="flex items-center gap-2 ml-4"><button onClick={()=>setShowProfile(true)} className="flex items-center gap-2 px-3 py-1.5 bg-gray-100 hover:bg-gray-200 text-gray-800 rounded-lg text-xs font-medium transition-colors" title="View Profile & Account">{(user?.user_metadata?.avatar_url || user?.user_metadata?.picture) ? <img src={user?.user_metadata?.avatar_url || user?.user_metadata?.picture} alt="Avatar" className="w-5 h-5 rounded-full object-cover" /> : <span className="w-5 h-5 rounded-full bg-blue-600 text-white flex items-center justify-center text-[10px] font-bold">{user?.user_metadata?.full_name?.slice(0,1).toUpperCase()||'C'}</span>}<span>{user?.user_metadata?.full_name?.split(' ')[0]||'Profile'}</span></button>{onLogout&&<button onClick={onLogout} className="button outline text-xs">Sign out</button>}</div>}</div></header><div className="page-content relative" id="main-content" tabIndex={-1}>
 {role === 'guest' && <div className="absolute inset-0 z-20 flex flex-col items-center pt-40 bg-white/50 backdrop-blur-sm"><ShieldCheck size={48} className="text-blue-600 mb-4" /><h2 className="text-2xl font-bold text-gray-900 mb-2">Authentication Required</h2><p className="text-gray-600 mb-6 max-w-md text-center">You must log in to view detailed MPLADS public funds, visible progress, and accountability records.</p><button onClick={onLoginRequest} className="button text-lg px-8 py-3 bg-blue-600 text-white border-none">Login / Sign Up</button></div>}
 <div className={role === 'guest' ? 'opacity-30 pointer-events-none select-none' : ''}>
 {view==='overview'&&<CivicBanner source onMap={()=>navigate('map')}/>}<div className="page-heading"><div><div className="eyebrow">ALL INDIA / MPLADS RECORDS</div><h1>{titles[view]}</h1><p>Explore every supplied work, its allocation, recommending MP and approval status.</p></div>{role==='official'&&<button className="button outline" disabled={loading||!!error} onClick={()=>save('mplads-filtered-works.csv',sourceCsv(filtered))}><ArrowDownToLine size={17}/>Export {count(filtered.length)} works</button>}</div>
 <div className="dataset-banner"><div><span className="dataset-dot"/><strong>Complete MPLADS dataset</strong><span>{manifest?`${count(manifest.recordCount)} works · 36 source files · recommendations ${manifest.recommendedFrom} to ${manifest.recommendedTo}`:'Loading all state and union-territory records…'}</span></div><button className="text-button" onClick={onAdvanced}>Demo & editable workspace <ArrowRight size={15}/></button></div>
 <div className="filters" id="project-explorer"><div className="search-field"><Search size={17}/><input aria-label="Search all MPLADS fields" placeholder="Search work ID, MP, village, authority…" value={filters.search} onChange={e=>filter('search',e.target.value)}/></div><Picker label="State" value={filters.state} options={['All states',...options.states]} onChange={v=>filter('state',v)}/><Picker label="Status" value={filters.status} options={role==='citizen'?['Ongoing']:['All statuses','Unsanctioned','Sanctioned','Ongoing','Completed','Not reported']} onChange={v=>filter('status',v)}/><button className="button outline" aria-expanded={advanced} onClick={()=>setAdvanced(!advanced)}><SlidersHorizontal size={16}/>More filters</button><button className="text-button" onClick={reset}>Reset</button></div>
 {advanced&&<div className="source-extra-filters"><label>Approval<Picker label="Approval" value={filters.approval} options={['All approvals','Action Pending','Approved by IDA','Rejected by IDA']} onChange={v=>filter('approval',v)}/></label><label>House<Picker label="House" value={filters.house} options={['All houses','Lok Sabha','Rajya Sabha']} onChange={v=>filter('house',v)}/></label><label>Work category<Picker label="Work category" value={filters.category} options={['All categories',...options.categories]} onChange={v=>filter('category',v)}/></label><label>Recommending MP<Picker label="Recommending MP" value={filters.mp} options={['All MPs',...options.mps]} onChange={v=>filter('mp',v)}/></label><label>Recommended from<input aria-label="Recommended from" type="date" value={filters.from} onChange={e=>filter('from',e.target.value)}/></label><label>Recommended through<input aria-label="Recommended through" type="date" value={filters.to} onChange={e=>filter('to',e.target.value)}/></label></div>}
 {filters.from&&filters.to&&filters.from>filters.to&&<p role="alert" className="error-banner">The start date must be on or before the end date.</p>}
 {error?<div className="error-banner" role="alert">{error} <button onClick={()=>{setLoading(true);setError('');setAttempt(n=>n+1);}}>Retry loading</button></div>:loading?<section className="panel source-loading" role="status"><Database size={30}/><h2>Loading the complete dataset</h2><p>Preparing 60,359 works for search, filtering and reports.</p></section>:<>
 <div className="source-result-count" aria-live="polite">{count(filtered.length)} of {count(rows.length)} works{filters!==deferred?' · Updating…':''}</div>
 {['overview','reports'].includes(view)&&<div className="stats-grid"><Metric title="Works in selection" value={count(filtered.length)} note={`${count(summary.completed)} marked completed in source`} icon={<Building2/>}/>{role==='official'&&<Metric title="Recorded allocation" value={compactMoney(summary.allocation)} note="Sum of ALLOCATION_AMOUNT · not expenditure" icon={<IndianRupee/>}/>}<Metric title="Recommending MPs" value={count(summary.mp)} note={`${groups.states.length} states / UTs with matching works`} icon={<Users/>}/>{role==='official'&&<Metric title="Pending IDA action" value={count(summary.pending)} note="Approval status is separate from work status" icon={<ShieldCheck/>}/>}</div>}
 {view==='overview'&&<><div className="report-grid">{bars('Top states by allocation',groups.states.slice(0,8),false,s=>{filter('state',s);navigate('projects');})}{bars('Work status',groups.statuses,true,s=>{filter('status',s);navigate('projects');})}</div><section className="panel"><div className="panel-heading"><div><h2>Project register</h2><p>Latest recommendation dates in this selection</p></div><button className="text-button" onClick={()=>navigate('projects')}>All works <ArrowRight size={16}/></button></div>{table([...filtered].sort((a,b)=>b.recommended.localeCompare(a.recommended)).slice(0,5))}</section><div className="insight-note"><Database size={23}/><div><strong>Source coverage</strong><p>The supplied records cover recommendations from 2023–2024. Expenditure, site coordinates, contractors, payment registers and physical progress were not supplied. Open any work to inspect all 16 original fields.</p></div></div></>}
 {view==='projects'&&<section className="panel"><div className="panel-heading"><h2>All works <span className="count">{count(filtered.length)}</span></h2><Picker label="Sort projects" value={sort} options={['Latest recommended','Highest allocation','Lowest allocation','Work ID']} onChange={v=>{setSort(v);setPage(1);}}/></div>{table(shown)}<div className="source-pagination"><span>{filtered.length?count((currentPage-1)*50+1):0}–{count(Math.min(currentPage*50,filtered.length))} of {count(filtered.length)}</span><button className="button outline" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}>Previous</button><label>Page <input type="number" aria-label="Project page" min={1} max={pages} value={currentPage} onChange={e=>setPage(Math.max(1,Math.min(pages,Number(e.target.value)||1)))}/> / {count(pages)}</label><button className="button outline" disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}>Next</button></div></section>}
 {view==='map'&&<><section className="panel geo-panel"><div className="panel-heading"><div><h2>Geo Intelligence <small className="hindi-section" lang="hi">भौगोलिक कवरेज</small></h2><p>{count(filtered.length)} works · constituency-level resolution · approximate</p></div></div><CesiumGlobe works={filtered} onSelect={w=>setSelected(w)} selectedId={selected?.id}/></section><div className="insight-note"><Building2 size={24}/><div><strong>Location precision</strong><p>Coordinates are resolved to constituency or state centroids using the supplied CONSTITUENCY and STATE fields. STATE may represent MP affiliation rather than work location. Markers tagged as approximate are positioned at geographic centroids, not verified addresses.</p></div></div><details className="geo-fallback-panel"><summary>Coverage confidence — allocation by state / UT</summary>{bars('Allocation by recorded state / UT',groups.states,false,s=>{filter('state',s);navigate('projects');})}</details></>}
 {view==='reports'&&<><div className="report-grid">{bars('Allocation by source category',groups.categories)}{bars('IDA approval status',groups.approvals,true)}{bars('Recommendation month',groups.months)}{bars('Top 10 MPs by allocation',groups.mps.slice(0,10))}</div><section className="panel"><div className="panel-heading"><h2>State / UT comparison</h2>{role==='official'&&<button className="button outline" onClick={exportReport}><ArrowDownToLine size={16}/>Export analysis</button>}</div><Table><TableHeader><TableRow><TableHead>STATE / UT</TableHead><TableHead>WORKS</TableHead>{role==='official'&&<TableHead>ALLOCATION (INR)</TableHead>}</TableRow></TableHeader><TableBody>{groups.states.map(g=><TableRow key={g.name}><TableCell><button className="text-button" onClick={()=>{filter('state',g.name);navigate('projects');}}>{g.name}</button></TableCell><TableCell>{count(g.count)}</TableCell>{role==='official'&&<TableCell>{money(g.allocation)}</TableCell>}</TableRow>)}</TableBody></Table></section></>}
 {view==='contractors'&&<><div className="insight-note"><Users size={24}/><div><strong>{count(groups.agencies.length)} implementing authorities in this selection</strong><p>The dataset names implementing authorities, but does not identify awarded contractors. Select an authority to inspect its works.</p></div></div><section className="panel"><div className="panel-heading"><h2>Implementing authorities</h2><span>Top 100 by allocation · search above to narrow</span></div><Table><TableHeader><TableRow><TableHead>AUTHORITY</TableHead><TableHead>WORKS</TableHead>{role==='official'&&<TableHead>ALLOCATION</TableHead>}</TableRow></TableHeader><TableBody>{groups.agencies.slice(0,100).map(g=><TableRow key={g.name}><TableCell><button className="text-button" onClick={()=>{filter('search',g.name);navigate('projects');}}>{g.name||'Not reported'}</button></TableCell><TableCell>{count(g.count)}</TableCell>{role==='official'&&<TableCell>{money(g.allocation)}</TableCell>}</TableRow>)}</TableBody></Table></section></>}
 {view==='alerts'&&<><div className="insight-note"><ShieldCheck size={24}/><div><strong>Data completeness review</strong><p>The original expenditure, delay and Isolation Forest checks need financial and progress fields absent from these CSVs. They cannot assess these works. Approval pending or rejected is a source status, not an allegation of fraud.</p></div></div><div className="stats-grid"><Metric title="Unreported work status" value={count(summary.missing)} note="Blank STATUS fields are preserved as unknown" icon={<Database/>}/><Metric title="Site coordinates" value="Not supplied" note="No verified project markers can be placed" icon={<Building2/>}/><Metric title="Expenditure & progress" value="Not supplied" note="Spending and delivery checks unavailable" icon={<IndianRupee/>}/><Metric title="Unique work IDs" value={count(filtered.length)} note="All source IDs validated during integration" icon={<ShieldCheck/>}/></div><section className="panel"><div className="panel-heading"><h2>Works with unreported status</h2><button className="text-button" onClick={()=>{filter('status','Not reported');navigate('projects');}}>Inspect all <ArrowRight size={16}/></button></div>{table(filtered.filter(r=>r.status==='Not reported').slice(0,10))}</section></>}
 {view==='feedback'&&<section className="panel"><div className="blank"><Users size={30}/><h3>Citizen feedback needs a connected workspace</h3><p>These source files contain no citizen reports. The existing editable workspace supports authenticated feedback, evidence uploads and review workflows for its project records.</p><button className="button" onClick={onAdvanced}>Open editable workspace <ArrowRight size={16}/></button></div></section>}
 {view==='data'&&manifest&&<><div className="insight-note"><Database size={24}/><div><strong>All 36 files integrated · {count(manifest.recordCount)} unique works</strong><p>Every source row and all 16 columns are retained. Chandigarh, Ladakh, and Dadra and Nagar Haveli and Daman and Diu contain headers only. Original CSV files are preserved in the project; each work links to its source filename and row.</p></div></div><div className="report-grid"><section className="panel"><div className="panel-heading"><h2>Dataset definitions</h2></div><dl className="details-list source-definitions"><div><dt>Source archive</dt><dd>{manifest.source}</dd></div><div><dt>Recommendation dates</dt><dd>{manifest.recommendedFrom} to {manifest.recommendedTo}</dd></div><div><dt>Total recorded allocation</dt><dd>{money(Number(manifest.allocationTotal))}</dd></div><div><dt>Unknown work status</dt><dd>{count(manifest.missingStatus)} records</dd></div><div><dt>Allocation meaning</dt><dd>Source allocation amount in INR. No inferred sanction, release or expenditure.</dd></div><div><dt>Verification</dt><dd>User-supplied snapshot; no connected government feed.</dd></div></dl></section><section className="panel"><div className="panel-heading"><h2>Downloads</h2></div><div className="source-downloads"><button className="button outline" onClick={()=>save('mplads-all-india.csv',sourceCsv(rows))}><ArrowDownToLine size={17}/>All {count(rows.length)} records (CSV)</button><button className="button outline" onClick={()=>save('mplads-manifest.json',JSON.stringify(manifest,null,2),'application/json')}><ArrowDownToLine size={17}/>File counts & SHA-256 checksums</button><button className="button outline" onClick={exportReport}><ArrowDownToLine size={17}/>Current selection analysis</button><p>Exports retain the original columns. Spreadsheet formula prefixes are escaped in CSV exports; original source files remain unchanged.</p></div></section></div><section className="panel"><div className="panel-heading"><h2>Source file inventory</h2><span>Full dataset · unaffected by filters</span></div><Table><TableHeader><TableRow><TableHead>STATE / UT</TableHead><TableHead>SOURCE FILE</TableHead><TableHead>ROWS</TableHead></TableRow></TableHeader><TableBody>{manifest.files.map(f=><TableRow key={f.name}><TableCell>{f.state}</TableCell><TableCell className="source-filename">{f.name}</TableCell><TableCell>{count(f.rows)}</TableCell></TableRow>)}</TableBody></Table></section></>}
  </>}</div><footer className="page-footer"><span>Nirmaan Watch · Code Crew · SIH 26102</span><span>Supplied MPLADS snapshot · allocations in INR</span></footer></div></main>
 <Sheet open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}}><SheetContent className="project-sheet"><SheetHeader><div className="eyebrow">{selected?.id}</div><SheetTitle>{selected?.title||'Work details'}</SheetTitle><SheetDescription>Original MPLADS source record · all supplied fields</SheetDescription></SheetHeader>{selected&&<><div className="detail-status"><Badge text={selected.status}/><Badge text={selected.approval}/></div><div className="source-allocation"><span>Recorded allocation</span><strong>{money(selected.allocation)}</strong><p>Not a reported expenditure or released-funds amount.</p></div><dl className="details-list">{columns.map((c,i)=><div key={c}><dt>{c.replaceAll('_',' ')}</dt><dd>{selected.raw[i]||'Not reported'}</dd></div>)}</dl><div className="source-box"><strong>Source trace</strong><p>{selected.file} · CSV row {selected.line} (header is row 1)</p><span>Recommendation date is not a start, completion or last-update date.</span></div>{role==='official'&&<button className="button outline" onClick={()=>save(`${selected.id}.csv`,sourceCsv([selected]))}><ArrowDownToLine size={16}/>Export this work</button>}<ProjectReviews projectId={selected.id} role={role} /></>}</SheetContent></Sheet>
  <ProfileModal user={user} role={role} isOpen={showProfile} onClose={()=>setShowProfile(false)} onLogout={()=>{setShowProfile(false);onLogout?.();}}/>
 </SidebarProvider>;
}
