import { env } from 'cloudflare:workers';
import { eq } from 'drizzle-orm';
import { getChatGPTUser } from '@/app/chatgpt-auth';
import { getDb } from '@/db';
import { documents, projects, audit } from '@/db/schema';
import { demoProjects } from '@/lib/demo';
export async function GET(request:Request){const user=await getChatGPTUser();if(!user)return new Response('Sign in required',{status:401});const id=new URL(request.url).searchParams.get('id')||'';const [doc]=await getDb().select().from(documents).where(eq(documents.id,id));if(!doc)return new Response('Not found',{status:404});const file=await env.BUCKET.get(id);if(!file)return new Response('File unavailable',{status:404});return new Response(file.body,{headers:{'Content-Type':doc.type,'Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(doc.name)}`,'X-Content-Type-Options':'nosniff','Cache-Control':'private, no-store'}});}
export async function POST(request:Request){try{if(request.headers.get('sec-fetch-site')==='cross-site'||(request.headers.get('origin')&&request.headers.get('origin')!==new URL(request.url).origin))return Response.json({error:'Cross-site request rejected'},{status:403});const user=await getChatGPTUser();if(!user)return Response.json({error:'Sign in required'},{status:401});if(Number(request.headers.get('content-length')||0)>5_300_000)throw new Error('Maximum upload size is 5 MB.');const form=await request.formData(),file=form.get('file'),projectId=String(form.get('projectId')||'');if(!(file instanceof File)||file.size>5_000_000||file.size===0)throw new Error('Choose a PDF, PNG or JPEG below 5 MB.');if(!demoProjects.some(p=>p.id===projectId)&&!(await getDb().select().from(projects).where(eq(projects.id,projectId)))[0])throw new Error('Project not found');
 const bytes=new Uint8Array(await file.arrayBuffer());const type=bytes[0]===0x25&&bytes[1]===0x50&&bytes[2]===0x44&&bytes[3]===0x46?'application/pdf':bytes[0]===0x89&&bytes[1]===0x50&&bytes[2]===0x4e&&bytes[3]===0x47?'image/png':bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff?'image/jpeg':null;if(!type)throw new Error('Only actual PDF, PNG, and JPEG files are accepted.');const id=crypto.randomUUID(),createdAt=new Date().toISOString(),name=file.name.replace(/[\x00-\x1f]/g,'').slice(0,180);await env.BUCKET.put(id,bytes,{httpMetadata:{contentType:type}});try{await getDb().batch([getDb().insert(documents).values({id,projectId,name,type,size:file.size,uploader:user.email,createdAt}),getDb().insert(audit).values({id:crypto.randomUUID(),actor:user.email,action:'Evidence uploaded',detail:`${projectId}: ${name} (unverified submission)`,createdAt})]);}catch(e){await env.BUCKET.delete(id);throw e;}return Response.json({ok:true});}catch(e){return Response.json({error:e instanceof Error?e.message:'Upload failed'},{status:400});}}
